# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os: linux
codecov: true
coveralls: true
julia:
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
branches:
  only: master
addons:
  apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - python3-pip
install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install seaborn
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'using Pkg; Pkg.build(); Pkg.test("EasyPlotting", coverage=true)'
notifications:
  email: false
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
